import 'package:dio/dio.dart';
import '../models/fact_check.dart';
import '../services/api_service.dart';

class FactChecksApi {
  final ApiService _apiService;

  FactChecksApi(this._apiService);

  /// Get latest fact checks
  Future<List<FactCheck>> getLatest({int limit = 20}) async {
    try {
      final response = await _apiService.dio.get(
        '/fact-checks',
        queryParameters: {'limit': limit},
      );

      final List<dynamic> data = response.data as List;
      return data.map((json) => _factCheckFromApi(json)).toList();
    } on DioException catch (e) {
      throw Exception('Failed to get fact checks: ${e.message}');
    }
  }

  /// Get fact check by ID
  Future<FactCheck?> getById(String checkId) async {
    try {
      final response = await _apiService.dio.get('/checks/$checkId');
      return _factCheckFromApi(response.data);
    } on DioException catch (e) {
      if (e.response?.statusCode == 404) {
        return null;
      }
      throw Exception('Failed to get fact check: ${e.message}');
    }
  }

  /// Get fact checks by categories
  Future<List<FactCheck>> getByCategories(List<String> categories) async {
    try {
      final categoriesParam = categories.join(',');
      final response = await _apiService.dio.get(
        '/fact-checks',
        queryParameters: {'categories': categoriesParam},
      );

      final List<dynamic> data = response.data as List;
      return data.map((json) => _factCheckFromApi(json)).toList();
    } on DioException catch (e) {
      throw Exception('Failed to get fact checks by categories: ${e.message}');
    }
  }

  /// Generate a new fact-check using AI
  Future<FactCheck> generateWithAI({
    required String question,
    String? category,
  }) async {
    try {
      final response = await _apiService.postWithExtendedTimeout(
        '/generate',
        data: {
          'question': question,
          if (category != null) 'category': category,
        },
      );

      return _factCheckFromApi(response.data);
    } on DioException catch (e) {
      throw Exception('Failed to generate fact-check: ${e.message}');
    }
  }

  /// Convert API response to FactCheck model
  FactCheck _factCheckFromApi(Map<String, dynamic> json) {
    // Map API verdict to our enum
    Verdict verdict;
    switch (json['verdict'] as String) {
      case 'true':
        verdict = Verdict.true_;
        break;
      case 'false':
        verdict = Verdict.false_;
        break;
      case 'mixed':
        verdict = Verdict.mixed;
        break;
      case 'unclear':
      default:
        verdict = Verdict.unclear;
        break;
    }

    return FactCheck(
      id: json['id'] as String,
      title: json['title'] as String,
      verdict: verdict,
      confidence: json['confidence'] as int,
      publishedAt: json['published_at'] != null
          ? DateTime.parse(json['published_at'] as String)
          : (json['created_at'] != null
                ? DateTime.parse(json['created_at'] as String)
                : DateTime.now()),
      autoGenerated: json['auto_generated'] as bool? ?? false,
      summary: json['summary'] as String?,
      category: json['category'] as String?,
      sources: json['sources'] != null
          ? List<String>.from(json['sources'])
          : null,
    );
  }
}
