import '../models/fact_check.dart';

abstract class FactCheckRepositoryInterface {
  Future<List<FactCheck>> getLatest();
  Future<FactCheck?> getById(String id);
  Future<List<FactCheck>> searchFactChecks(String query);
  Future<List<FactCheck>> getByVerdict(Verdict verdict);
  Future<List<FactCheck>> getAutoGenerated();
  Future<Map<Verdict, int>> getVerdictStatistics();
  Future<List<FactCheck>> getByCategories(List<String> categories);
}
