import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import '../providers/fact_check_providers.dart';
import '../features/home/home_providers.dart' as homeProviders;

/// Widget de debug pentru a monitoriza provider-ii în timp real
class ProviderDebugWidget extends ConsumerWidget {
  const ProviderDebugWidget({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final latestFactChecks = ref.watch(latestFactChecksProvider);
    final homeStatistics = ref.watch(homeStatisticsProvider);
    final stats = ref.watch(homeProviders.statsProvider);

    return Card(
      color: Colors.yellow.shade100,
      child: Padding(
        padding: const EdgeInsets.all(8.0),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Text(
              '🐛 DEBUG PROVIDERS',
              style: TextStyle(
                fontWeight: FontWeight.bold,
                color: Colors.red.shade700,
              ),
            ),
            const SizedBox(height: 8),
            Text('latestFactChecksProvider:'),
            latestFactChecks.when(
              data: (checks) => Text('  ✅ ${checks.length} fact-checks'),
              loading: () => const Text('  ⏳ Loading...'),
              error: (e, _) => Text('  ❌ Error: $e'),
            ),
            const SizedBox(height: 4),
            Text('homeStatisticsProvider:'),
            homeStatistics.when(
              data: (stats) => Text('  ✅ Total: ${stats['total']}, Auto: ${stats['autoGenerated']}, Manual: ${stats['manual']}'),
              loading: () => const Text('  ⏳ Loading...'),
              error: (e, _) => Text('  ❌ Error: $e'),
            ),
            const SizedBox(height: 4),
            Text('statsProvider:'),
            stats.when(
              data: (statsData) => Text('  ✅ Count: ${statsData['newCount']}, Auto%: ${statsData['autoGeneratedPct']}, Edit%: ${statsData['editorialPct']}'),
              loading: () => const Text('  ⏳ Loading...'),
              error: (e, _) => Text('  ❌ Error: $e'),
            ),
            const SizedBox(height: 8),
            Row(
              children: [
                ElevatedButton(
                  onPressed: () {
                    ref.invalidate(latestFactChecksProvider);
                  },
                  child: const Text('Refresh Latest'),
                ),
                const SizedBox(width: 8),
                ElevatedButton(
                  onPressed: () {
                    ref.invalidate(homeStatisticsProvider);
                  },
                  child: const Text('Refresh Stats'),
                ),
              ],
            ),
          ],
        ),
      ),
    );
  }
}
