import 'package:flutter/material.dart';
import '../models/fact_check.dart';
import '../utils/verdict_extensions.dart';

class VerdictBadge extends StatelessWidget {
  final FactCheck factCheck;
  final double fontSize;
  final double iconSize;
  final EdgeInsets padding;

  const VerdictBadge({
    super.key,
    required this.factCheck,
    this.fontSize = 12,
    this.iconSize = 14,
    this.padding = const EdgeInsets.symmetric(horizontal: 8, vertical: 4),
  });

  @override
  Widget build(BuildContext context) {
    return Container(
      padding: padding,
      decoration: BoxDecoration(
        color: factCheck.verdict.color.withValues(alpha: 0.1),
        borderRadius: BorderRadius.circular(8),
        border: Border.all(
          color: factCheck.verdict.color.withValues(alpha: 0.3),
        ),
      ),
      child: Row(
        mainAxisSize: MainAxisSize.min,
        children: [
          Icon(
            factCheck.verdict.iconData,
            size: iconSize,
            color: factCheck.verdict.color,
          ),
          const SizedBox(width: 4),
          Text(
            factCheck.verdict.displayName,
            style: TextStyle(
              fontSize: fontSize,
              fontWeight: FontWeight.w600,
              color: factCheck.verdict.color,
            ),
          ),
        ],
      ),
    );
  }
}

class GenerationTypeBadge extends StatelessWidget {
  final FactCheck factCheck;
  final double fontSize;
  final double iconSize;
  final EdgeInsets padding;

  const GenerationTypeBadge({
    super.key,
    required this.factCheck,
    this.fontSize = 12,
    this.iconSize = 16,
    this.padding = const EdgeInsets.symmetric(horizontal: 6, vertical: 2),
  });

  @override
  Widget build(BuildContext context) {
    return Container(
      padding: padding,
      decoration: BoxDecoration(
        color: factCheck.autoGenerated
            ? Colors.blue.withValues(alpha: 0.1)
            : Colors.green.withValues(alpha: 0.1),
        borderRadius: BorderRadius.circular(8),
      ),
      child: Row(
        mainAxisSize: MainAxisSize.min,
        children: [
          Icon(
            factCheck.autoGenerated ? Icons.smart_toy : Icons.verified,
            size: iconSize,
            color: factCheck.autoGenerated
                ? Colors.blue.shade700
                : Colors.green.shade700,
          ),
          const SizedBox(width: 2),
          Text(
            factCheck.autoGenerated ? 'Automat' : 'Editorial',
            style: TextStyle(
              fontSize: fontSize,
              fontWeight: FontWeight.w600,
              color: factCheck.autoGenerated
                  ? Colors.blue.shade700
                  : Colors.green.shade700,
            ),
          ),
        ],
      ),
    );
  }
}
