// lib/features/home/home_providers.dart
import 'package:flutter_riverpod/flutter_riverpod.dart';
import '../../providers/fact_check_providers.dart';

// Provider pentru tipul de fact-check (toate, automate, manuale)
final factCheckTypeProvider = StateProvider<String>((_) => 'toate');

// Provider pentru statistici reale bazat pe latestFactChecksProvider
final statsProvider = FutureProvider<Map<String, dynamic>>((ref) async {
  // Use the same data source as homeStatisticsProvider
  final homeStats = await ref.watch(homeStatisticsProvider.future);
  final total = homeStats['total'] as int;
  final autoGenerated = homeStats['autoGenerated'] as int;
  final manual = homeStats['manual'] as int;

  // Calculăm procentele
  final autoGeneratedPct = total > 0
      ? ((autoGenerated / total) * 100).round()
      : 0;
  final editorialPct = total > 0 ? ((manual / total) * 100).round() : 0;

  return {
    'newCount': total,
    'autoGeneratedPct': autoGeneratedPct,
    'editorialPct': editorialPct,
  };
});
